spring:
  flyway:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  datasource:
    diverClassName: org.h2.Driver
    url: jdbc:h2:~/quotes
    username: sa
    password: